name: CI

# Trigger workflow on push or pull request to main branch, or manually
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - uses: actions/checkout@v4

      # Step 2: Run Markdown lint
      - name: Run markdown lint
        run: |
          npm install remark-cli remark-preset-lint-consistent vfile-reporter-json
          npx remark . --use remark-preset-lint-consistent --report vfile-reporter-json 2> remark-lint-report.json

      # Step 3: Upload lint report as artifact
      - uses: actions/upload-artifact@v4
        with:
          name: remark-lint-report
          path: remark-lint-report.json
