name: CI Workflow

on:
  push:
    branches:
      - main
      - '**/feature/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Run markdown lint and output JSON report
      - name: Run markdown lint
        run: |
          npm install remark-cli remark-preset-lint-consistent vfile-reporter-json
          npx remark . --use remark-preset-lint-consistent --report vfile-reporter-json 2> remark-lint-report.json

      # Step 3: Upload the report as an artifact
      - name: Upload markdown lint report
        uses: actions/upload-artifact@v4
        with:
          name: remark-lint-report
          path: remark-lint-report.json
